name: Deploy to Surge

on:
  push:
    branches:
      - main  # Asegúrate de que el nombre de la rama coincida

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - name: Installing surge    
      run: npm install --global surge

    - name: Deploy to Surge
      run: surge ./src luis-p1.sh --token ${{secrets.SURGE_TOKEN}}
