name: Deploy a Surge

on:
  push:
    branches:
      - main  # Ejecutar la acción solo en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Versión de Node.js

      - name: Install dependencies
        run: npm install

      - name: Deploy to Surge
        run: npm run deploy
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  # El token de Surge, lo guardas como secreto en GitHub
