name: Deploy to Surge

on:
  push:
    branches:
      - main  # Asegúrate de que el nombre de la rama coincida

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - run: npm install --global surge

    - name: Deploy to Surge
      run: surge ./src https://luis-p1.surge.sh --token ${{ secrets.SECRET_TOKEN }}
